### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by joemccann** [01protocol/zo-keeper#15]
After cloning and including the submodules, running the code `cargo build --release` yields a compilation error in the `ABI`.

<img width="909" alt="CleanShot 2022-03-04 at 07 01 05@2x" src="https://user-images.githubusercontent.com/48234/156786990-6756576b-9686-4b80-9eaa-c7f82ec2de7a.png">

Rust version: rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by jakeburden** [comment]
This PR in zo-abi seems to fix the compilation error: https://github.com/01protocol/zo-abi/pull/5

Steps I ran:

Change .gitmodules
```
[submodule "abi"]
  path = abi
  url = https://github.com/01protocol/zo-abi.git
  branch = phils-changes
```

Update submodules:
```
git submodule update --remote
git submodule update --init
```

Compile:
`cargo build --release`

Run:
`./target/release/zo-keeper --rpc-url "https://api.mainnet-beta.solana.com/" --ws-url "wss://[api.mainnet-beta.solana.com:8900](https://api.mainnet-beta.solana.com:8900/)" liquidator --worker-count 1 --worker-index 0`

Note (might be a different issue), even though this fixes the compilation, I get a websocket timeout when running the liquidator. This could be an issue with the RPC though.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2081699/156819534-514f0cfd-f7f6-49f8-9473-0fc9a508cab5.png">
